(() => {
'use strict';
const SOURCE='data/source/faurgs_ifsc_questoes_integrais_stage2.json';
const STORAGE={session:'faurgs.simulados.session.v1',history:'faurgs.simulados.history.v1'};
const state={raw:null,questions:[],supports:new Map(),history:{},session:null,resultSession:null,timer:null};
const $=id=>document.getElementById(id); const views=['loadingView','homeView','quizView','resultView'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:'instant'});}function toast(msg,t=2200){const e=$('toast');e.textContent=msg;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),t);}function parse(raw,f){try{return raw?JSON.parse(raw):f}catch{return f}}
function isAnnulled(q){const s=String(q.situacao||q.status||'').toLowerCase(),g=String(q.gabarito||q.gabarito_historico||'').toLowerCase();return q.anulada===true||q.anulado===true||s.includes('anulad')||g.includes('anulad')||q.id==='TJRS16-PED-Q26';}
function alternatives(q){if(q.alternativas&&typeof q.alternativas==='object'&&!Array.isArray(q.alternativas))return q.alternativas;const a={};for(const l of ['A','B','C','D','E'])if(q[l]!=null)a[l]=q[l];return a;}
function normalize(raw){const supportsRaw=raw.textos_apoio||raw.suportes||[];state.supports=new Map(supportsRaw.map(s=>[s.apoio_id||s.id,s]));const list=raw.questoes||raw.questions||[];return list.map((q,i)=>{const alts=alternatives(q);const support=q.texto_apoio||state.supports.get(q.apoio_id)?.texto||'';const key=String(q.gabarito||q.gabarito_historico||'').trim().toUpperCase();return{...q,id:String(q.id||`FAURGS-${i+1}`),disciplina:String(q.disciplina||'Sem disciplina'),tema:String(q.tema||'Sem tema'),concurso:String(q.concurso||q.orgao||'FAURGS'),ano:q.ano||'',enunciado:String(q.enunciado||q.questao||''),alternativas:alts,gabarito:/^[A-E]$/.test(key)?key:'',support,url_fonte:q.url_fonte||'',annulled:isAnnulled(q)};}).filter(q=>q.enunciado&&Object.keys(q.alternativas).length>=2);}
function uniq(vals){return [...new Set(vals.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true}));}function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}function qById(id){return state.questions.find(q=>q.id===id);}function hist(id){return state.history[id]||null;}
function populate(){const make=(el,all,vals)=>{$(el).innerHTML=`<option value="all">${all}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');};make('examSelect','Todos os concursos',uniq(state.questions.map(q=>q.concurso)));make('disciplineSelect','Todas as disciplinas',uniq(state.questions.map(q=>q.disciplina)));updateTopics();}
function updateTopics(){const d=$('disciplineSelect').value,e=$('examSelect').value;const pool=state.questions.filter(q=>(d==='all'||q.disciplina===d)&&(e==='all'||q.concurso===e));$('topicSelect').innerHTML='<option value="all">Todos os temas</option>'+uniq(pool.map(q=>q.tema)).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');refreshPool();}
function filtered(){const e=$('examSelect').value,d=$('disciplineSelect').value,t=$('topicSelect').value,h=$('historyFilter').value,exclude=$('excludeAnnulled').checked;return state.questions.filter(q=>{if(e!=='all'&&q.concurso!==e)return false;if(d!=='all'&&q.disciplina!==d)return false;if(t!=='all'&&q.tema!==t)return false;if(exclude&&q.annulled)return false;const x=hist(q.id);if(h==='unseen'&&x)return false;if(h==='wrong'&&!(x&&x.lastCorrect===false))return false;if(h==='review'&&!(x&&x.review))return false;return true;});}
function refreshPool(){const p=filtered(),n=Math.max(1,Number($('quantityInput').value)||1);$('poolInfo').textContent=`${p.length} questão(ões) disponíveis${n>p.length?' — reduza a quantidade.':'.'}`;$('customBtn').disabled=!p.length||n>p.length;}
function saveHistory(){localStorage.setItem(STORAGE.history,JSON.stringify(state.history));}function saveSession(){if(!state.session)return;state.session.updatedAt=Date.now();localStorage.setItem(STORAGE.session,JSON.stringify(state.session));}
function formatTime(sec){sec=Math.max(0,Math.floor(sec));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}function elapsed(s=state.session){return s?Math.max(0,Math.floor((Date.now()-s.startedAt)/1000)-(s.pausedSeconds||0)):0;}function stopTimer(){if(state.timer)clearInterval(state.timer);state.timer=null;$('timerTop').classList.add('timer--hidden');}function startTimer(){stopTimer();$('timerTop').classList.remove('timer--hidden');const tick=()=>{if(state.session)$('timerTop').textContent=formatTime(elapsed())};tick();state.timer=setInterval(tick,1000);}
function renderHome(){stopTimer();show('homeView');const valid=state.questions.filter(q=>!q.annulled&&q.gabarito).length;const stats=[[state.questions.length,'questões carregadas'],[valid,'pontuáveis'],[uniq(state.questions.map(q=>q.disciplina)).length,'disciplinas'],[uniq(state.questions.map(q=>q.concurso)).length,'concursos']];$('heroStats').innerHTML=stats.map(([n,l])=>`<div class="stat-box"><strong>${n}</strong><span>${l}</span></div>`).join('');const answered=Object.keys(state.history).length,correct=Object.values(state.history).filter(x=>x.lastCorrect===true).length,review=Object.values(state.history).filter(x=>x.review).length;$('historyStats').innerHTML=[[answered,'já vistas'],[correct,'último acerto'],[review,'para revisar']].map(([n,l])=>`<div class="mini-stat"><strong>${n}</strong><span>${l}</span></div>`).join('');const s=parse(localStorage.getItem(STORAGE.session),null),ok=s&&Array.isArray(s.questionIds)&&s.questionIds.length&&!s.completed;$('resumeCard').classList.toggle('hidden',!ok);if(ok){const n=Object.values(s.responses||{}).filter(Boolean).length;$('resumeText').textContent=`${n} de ${s.questionIds.length} respondidas. O progresso foi salvo automaticamente.`;}refreshPool();}
function makeSession(ids,label,mode){return{version:1,id:`SIM-${Date.now()}`,label,mode,questionIds:ids,currentIndex:0,responses:{},reviews:{},startedAt:Date.now(),pausedSeconds:0,updatedAt:Date.now(),completed:false};}function startSession(s){state.session=s;saveSession();show('quizView');startTimer();renderQuestion();}
function custom(){const p=filtered(),n=Math.max(1,Number($('quantityInput').value)||1);if(n>p.length)return toast('Não há questões suficientes neste recorte.');const label=[$('examSelect').selectedOptions[0]?.textContent,$('disciplineSelect').selectedOptions[0]?.textContent,$('topicSelect').value==='all'?'':$('topicSelect').selectedOptions[0]?.textContent].filter(Boolean).join(' • ');startSession(makeSession(shuffle(p).slice(0,n).map(q=>q.id),label,'custom'));}
function mixed(){const p=state.questions.filter(q=>!q.annulled&&q.gabarito);if(!p.length)return toast('Banco sem questões pontuáveis.');const n=Math.min(20,p.length);startSession(makeSession(shuffle(p).slice(0,n).map(q=>q.id),`Treino misto FAURGS • ${n} questões`,'mixed'));}
function resume(){const s=parse(localStorage.getItem(STORAGE.session),null);if(!s)return renderHome();if(s.questionIds.some(id=>!qById(id))){localStorage.removeItem(STORAGE.session);toast('A sessão salva não combina com o banco atual.');return renderHome();}s.pausedSeconds=(s.pausedSeconds||0)+Math.max(0,Math.floor((Date.now()-(s.updatedAt||Date.now()))/1000));startSession(s);}
function renderQuestion(){const s=state.session;if(!s)return renderHome();const q=qById(s.questionIds[s.currentIndex]);if(!q)return;$('progressText').textContent=`Questão ${s.currentIndex+1} de ${s.questionIds.length}`;$('progressBar').style.width=`${(s.currentIndex+1)/s.questionIds.length*100}%`;$('prevBtn').disabled=s.currentIndex===0;$('nextBtn').textContent=s.currentIndex===s.questionIds.length-1?'Finalizar →':'Próxima →';$('questionChips').innerHTML=[`<span class="chip primary">${esc(q.id)}</span>`,`<span class="chip">${esc(q.disciplina)}</span>`,`<span class="chip">${esc(q.tema)}</span>`,`<span class="chip">${esc(q.concurso)}${q.ano?` • ${esc(q.ano)}`:''}</span>`,q.annulled?'<span class="chip">ANULADA</span>':''].filter(Boolean).join('');$('knownBadge').classList.toggle('hidden',!hist(q.id));const hasSupport=!!q.support;$('supportBlock').classList.toggle('hidden',!hasSupport);if(hasSupport){$('supportContent').textContent=q.support;$('supportContent').classList.add('hidden');$('supportToggle').setAttribute('aria-expanded','false');}$('questionStatement').textContent=q.enunciado;$('sourceWrap').classList.toggle('hidden',!q.url_fonte);if(q.url_fonte)$('sourceLink').href=q.url_fonte;const selected=s.responses[q.id]||'';$('alternatives').innerHTML=Object.entries(q.alternativas).map(([l,text])=>`<label class="alt-option${selected===l?' selected':''}" data-letter="${esc(l)}"><input type="radio" name="answer" value="${esc(l)}" ${selected===l?'checked':''}/><div><span class="alt-letter">${esc(l)}</span><span class="alt-text">${esc(text)}</span></div></label>`).join('');$('alternatives').querySelectorAll('input[name=answer]').forEach(input=>input.addEventListener('change',()=>{s.responses[q.id]=input.value;$('alternatives').querySelectorAll('.alt-option').forEach(el=>el.classList.toggle('selected',el.dataset.letter===input.value));saveSession();}));const r=s.reviews[q.id]||{};$('reviewCheck').checked=!!r.marked;$('reviewReason').value=r.reason||'';$('reviewNote').value=r.note||'';$('reviewReasonWrap').classList.toggle('hidden',!r.marked);saveSession();}
function captureReview(){const s=state.session;if(!s)return;const q=qById(s.questionIds[s.currentIndex]);s.reviews[q.id]={marked:$('reviewCheck').checked,reason:$('reviewReason').value,note:$('reviewNote').value.trim()};saveSession();}function go(delta){captureReview();const s=state.session,n=s.currentIndex+delta;if(n>=s.questionIds.length)return finish();if(n<0)return;s.currentIndex=n;renderQuestion();window.scrollTo({top:0,behavior:'smooth'});}
function finish(){captureReview();const s=state.session;if(!s)return;const blank=s.questionIds.filter(id=>!s.responses[id]).length;if(blank&&!confirm(`Há ${blank} questão(ões) sem resposta. Deseja finalizar mesmo assim?`))return;s.completed=true;s.completedAt=Date.now();s.elapsedSeconds=elapsed(s);state.resultSession=JSON.parse(JSON.stringify(s));updateHistory(s);localStorage.removeItem(STORAGE.session);state.session=null;stopTimer();renderResults(state.resultSession);}
function updateHistory(s){for(const id of s.questionIds){const q=qById(id),answer=s.responses[id]||'',scorable=!q.annulled&&!!q.gabarito,correct=scorable&&!!answer&&answer===q.gabarito,r=s.reviews[id]||{},prev=state.history[id]||{attempts:0,correctCount:0,wrongCount:0};state.history[id]={...prev,attempts:(prev.attempts||0)+1,correctCount:(prev.correctCount||0)+(correct?1:0),wrongCount:(prev.wrongCount||0)+(scorable&&!correct?1:0),lastAnswer:answer,lastCorrect:scorable?correct:null,lastAt:Date.now(),review:!!r.marked,reviewReason:r.reason||'',reviewNote:r.note||''};}saveHistory();}
function reviewLabel(c){return{duvida:'dúvida entre alternativas',conteudo:'conteúdo desconhecido ou esquecido',comando:'comando / leitura operacional',raciocinio:'raciocínio incompleto',outro:'outro'}[c]||'sem motivo informado';}
function rowsFor(s){return s.questionIds.map(id=>{const q=qById(id),answer=s.responses[id]||'',valid=!q.annulled&&!!q.gabarito,correct=valid&&!!answer&&answer===q.gabarito;return{q,answer,valid,correct,review:s.reviews[id]||{}};});}
function renderResults(s){show('resultView');const rows=rowsFor(s),sc=rows.filter(r=>r.valid),hits=sc.filter(r=>r.correct).length,pct=sc.length?Math.round(hits/sc.length*100):0;$('resultTitle').textContent=s.label;$('scoreBig').textContent=`${hits}/${sc.length}`;$('resultMeta').textContent=`${pct}% de acertos • ${formatTime(s.elapsedSeconds||0)} • ${rows.filter(r=>!r.answer).length} em branco • ${rows.filter(r=>!r.valid).length} não pontuável(is)`;const groups={};rows.filter(r=>r.valid).forEach(r=>{groups[r.q.disciplina]||={total:0,hits:0};groups[r.q.disciplina].total++;if(r.correct)groups[r.q.disciplina].hits++;});$('disciplineResults').innerHTML=Object.entries(groups).map(([n,g])=>`<div class="result-row"><span>${esc(n)}</span><strong>${g.hits}/${g.total} • ${Math.round(g.hits/g.total*100)}%</strong></div>`).join('')||'<p>Sem questões pontuáveis.</p>';$('diagnosticResults').innerHTML=[['Erros / brancos',rows.filter(r=>r.valid&&!r.correct).length],['Marcadas para revisão',rows.filter(r=>r.review.marked).length],['Em branco',rows.filter(r=>!r.answer).length],['Não pontuáveis',rows.filter(r=>!r.valid).length]].map(([l,n])=>`<div class="result-row"><span>${l}</span><strong>${n}</strong></div>`).join('');$('reportOutput').value=report(s,rows);$('questionResults').innerHTML=rows.map(r=>{const status=!r.answer?'blank':r.valid?(r.correct?'ok':'wrong'):'blank',label=!r.valid?'não pontuável':!r.answer?'em branco':r.correct?'correta':'incorreta',rev=r.review.marked?` • revisar: ${reviewLabel(r.review.reason)}${r.review.note?` — ${r.review.note}`:''}`:'';return `<div class="question-result"><span class="result-dot ${status}"></span><div><strong>${esc(r.q.id)}</strong><div class="result-detail">${esc(r.q.disciplina)} • ${esc(r.q.tema)} • ${label}${esc(rev)}</div></div><div class="result-answer">${esc(r.answer||'—')} / ${esc(r.q.gabarito||'—')}</div></div>`;}).join('');$('retryWrongBtn').disabled=!rows.some(r=>r.valid&&!r.correct);}
function reportText(v){
  let t=String(v??'')
    .replace(/\r\n?/g,'\n')
    .replace(/<br\s*\/?>/gi,'\n')
    .replace(/<(?:strong|b)>([\s\S]*?)<\/(?:strong|b)>/gi,'**$1**')
    .replace(/<(?:em|i)>([\s\S]*?)<\/(?:em|i)>/gi,'*$1*')
    .replace(/<u>([\s\S]*?)<\/u>/gi,'++$1++')
    .replace(/<[^>]+>/g,'');
  const decoder=document.createElement('textarea');
  decoder.innerHTML=t;
  return decoder.value.replace(/[ \t]+\n/g,'\n').trim();
}
function report(s,rows){
  const sc=rows.filter(r=>r.valid),hits=sc.filter(r=>r.correct).length,disc=uniq(rows.map(r=>r.q.disciplina)).join(', ');
  const lines=[
    'SIMULADO: '+s.id,
    'Modelo: '+s.label,
    'Disciplinas: '+disc,
    'Questões: '+rows.length,
    'Concluído em: '+new Date(s.completedAt||Date.now()).toLocaleString('pt-BR'),
    'Tempo: '+formatTime(s.elapsedSeconds||0),
    'Resultado: '+hits+'/'+sc.length+' ('+(sc.length?Math.round(hits/sc.length*100):0)+'%)',
    '',
    'RESPOSTAS:'
  ];
  rows.forEach((r,i)=>{
    const num='Q'+String(i+1).padStart(2,'0');
    const status=!r.valid?'NÃO PONTUÁVEL':!r.answer?'EM BRANCO':r.correct?'CORRETA':'INCORRETA';
    let l=num+' ['+r.q.id+']: '+(r.answer||'-')+' / '+(r.q.gabarito||'-')+' | '+status;
    if(r.review.marked)l+=' | PARA REVISAR | '+reviewLabel(r.review.reason)+(r.review.note?' | '+r.review.note:'');
    lines.push(l);
  });
  lines.push('','QUESTÕES COMPLETAS:','');
  rows.forEach((r,i)=>{
    const num='Q'+String(i+1).padStart(2,'0');
    const status=!r.valid?'NÃO PONTUÁVEL':!r.answer?'EM BRANCO':r.correct?'CORRETA':'INCORRETA';
    lines.push(num+' ['+r.q.id+']');
    lines.push([
      'Disciplina: '+r.q.disciplina,
      'Tema: '+r.q.tema,
      r.q.concurso?'Concurso: '+r.q.concurso:'',
      r.q.ano?'Ano: '+r.q.ano:''
    ].filter(Boolean).join(' • '));
    lines.push('Resposta: '+(r.answer||'-')+' | Gabarito: '+(r.q.gabarito||'-')+' | Status: '+status);
    if(r.review.marked)lines.push('Revisão: '+reviewLabel(r.review.reason)+(r.review.note?' | '+r.review.note:''));
    if(r.q.support)lines.push('','TEXTO-BASE:',reportText(r.q.support));
    lines.push('','ENUNCIADO:',reportText(r.q.enunciado),'','ALTERNATIVAS:');
    Object.entries(r.q.alternativas).forEach(([letter,text])=>lines.push(letter+') '+reportText(text)));
    if(r.q.url_fonte)lines.push('','Fonte: '+r.q.url_fonte);
    lines.push('','---','');
  });
  return lines.join('\n').trimEnd();
}
function retryWrong(){const s=state.resultSession;if(!s)return;const ids=rowsFor(s).filter(r=>r.valid&&!r.correct).map(r=>r.q.id);if(!ids.length)return toast('Não há erros para retreinar.');startSession(makeSession(shuffle(ids),'Retreino • erros da sessão anterior','retry'));}
function bind(){$('examSelect').addEventListener('change',updateTopics);$('disciplineSelect').addEventListener('change',updateTopics);$('topicSelect').addEventListener('change',refreshPool);$('historyFilter').addEventListener('change',refreshPool);$('quantityInput').addEventListener('input',refreshPool);$('excludeAnnulled').addEventListener('change',refreshPool);$('customBtn').addEventListener('click',custom);$('mixedBtn').addEventListener('click',mixed);$('resumeBtn').addEventListener('click',resume);$('discardBtn').addEventListener('click',()=>{localStorage.removeItem(STORAGE.session);renderHome();toast('Sessão descartada.');});$('clearHistoryBtn').addEventListener('click',()=>{if(confirm('Apagar todo o histórico deste dispositivo?')){state.history={};saveHistory();renderHome();toast('Histórico apagado.');}});$('supportToggle').addEventListener('click',()=>{const c=$('supportContent'),open=c.classList.toggle('hidden')===false;$('supportToggle').setAttribute('aria-expanded',String(open));});$('reviewCheck').addEventListener('change',()=>{$('reviewReasonWrap').classList.toggle('hidden',!$('reviewCheck').checked);captureReview();});$('reviewReason').addEventListener('change',captureReview);$('reviewNote').addEventListener('input',captureReview);$('prevBtn').addEventListener('click',()=>go(-1));$('nextBtn').addEventListener('click',()=>go(1));$('finishTopBtn').addEventListener('click',finish);$('backHomeBtn').addEventListener('click',renderHome);$('retryWrongBtn').addEventListener('click',retryWrong);$('copyReportBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('reportOutput').value)}catch{$('reportOutput').select();document.execCommand('copy')}toast('Relatório copiado.');});}
async function init(){try{state.history=parse(localStorage.getItem(STORAGE.history),{});const res=await fetch(SOURCE,{cache:'no-store'});if(!res.ok)throw new Error(`Falha ao carregar o banco (${res.status})`);state.raw=await res.json();state.questions=normalize(state.raw);if(!state.questions.length)throw new Error('Nenhuma questão utilizável encontrada no stage2.');populate();bind();renderHome();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});}catch(err){$('loadingView').innerHTML=`<h1>Não foi possível abrir o banco</h1><p>${esc(err.message)}</p><p>Abra o simulador pelo GitHub Pages/servidor web; acesso direto por arquivo local não é suportado.</p>`;}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
